apiVersion: v1
kind: Secret
metadata:
  name: mobimeo-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  JWT_SECRET: {{ .Values.env.JWT_SECRET }}
  DB_NAME: {{ .Values.env.DB_NAME }}
  DB_USER: {{ .Values.env.DB_USER }}
  DB_HOST: {{ .Values.env.DB_HOST }}
  DB_PASS: {{ .Values.env.DB_PASS }}
  NODE_ENV: {{ .Values.env.NODE_ENV }}
  SERVICE_URL: {{ .Values.env.SERVICE_URL }}
  SERVICE_NAME: {{ .Values.env.SERVICE_NAME }}
